/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedEstoqueDotjsonRouteImport } from './routes/feed/estoque[.]json'
import { Route as ApiPublicVehicleImageRouteImport } from './routes/api/public/vehicle-image'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedEstoqueDotjsonRoute = FeedEstoqueDotjsonRouteImport.update({
  id: '/feed/estoque.json',
  path: '/feed/estoque.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVehicleImageRoute = ApiPublicVehicleImageRouteImport.update({
  id: '/api/public/vehicle-image',
  path: '/api/public/vehicle-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/feed/estoque.json': typeof FeedEstoqueDotjsonRoute
  '/api/public/vehicle-image': typeof ApiPublicVehicleImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/feed/estoque.json': typeof FeedEstoqueDotjsonRoute
  '/api/public/vehicle-image': typeof ApiPublicVehicleImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/feed/estoque.json': typeof FeedEstoqueDotjsonRoute
  '/api/public/vehicle-image': typeof ApiPublicVehicleImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/feed/estoque.json'
    | '/api/public/vehicle-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/feed/estoque.json'
    | '/api/public/vehicle-image'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/feed/estoque.json'
    | '/api/public/vehicle-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FeedEstoqueDotjsonRoute: typeof FeedEstoqueDotjsonRoute
  ApiPublicVehicleImageRoute: typeof ApiPublicVehicleImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/estoque.json': {
      id: '/feed/estoque.json'
      path: '/feed/estoque.json'
      fullPath: '/feed/estoque.json'
      preLoaderRoute: typeof FeedEstoqueDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vehicle-image': {
      id: '/api/public/vehicle-image'
      path: '/api/public/vehicle-image'
      fullPath: '/api/public/vehicle-image'
      preLoaderRoute: typeof ApiPublicVehicleImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FeedEstoqueDotjsonRoute: FeedEstoqueDotjsonRoute,
  ApiPublicVehicleImageRoute: ApiPublicVehicleImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
