/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedEstoqueDotjsonRouteImport } from './routes/feed/estoque[.]json'
import { Route as AuthenticatedIntegradorRouteImport } from './routes/_authenticated/integrador'
import { Route as ApiPublicVehicleImageRouteImport } from './routes/api/public/vehicle-image'
import { Route as AuthenticatedIntegracoesMercadoLivreRouteImport } from './routes/_authenticated/integracoes/mercado-livre'
import { Route as ApiPublicIntegrationsMercadolivreNotificationsRouteImport } from './routes/api/public/integrations/mercadolivre/notifications'
import { Route as ApiPublicIntegrationsMercadolivreCallbackRouteImport } from './routes/api/public/integrations/mercadolivre/callback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedEstoqueDotjsonRoute = FeedEstoqueDotjsonRouteImport.update({
  id: '/feed/estoque.json',
  path: '/feed/estoque.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntegradorRoute = AuthenticatedIntegradorRouteImport.update({
  id: '/integrador',
  path: '/integrador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicVehicleImageRoute = ApiPublicVehicleImageRouteImport.update({
  id: '/api/public/vehicle-image',
  path: '/api/public/vehicle-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntegracoesMercadoLivreRoute =
  AuthenticatedIntegracoesMercadoLivreRouteImport.update({
    id: '/integracoes/mercado-livre',
    path: '/integracoes/mercado-livre',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicIntegrationsMercadolivreNotificationsRoute =
  ApiPublicIntegrationsMercadolivreNotificationsRouteImport.update({
    id: '/api/public/integrations/mercadolivre/notifications',
    path: '/api/public/integrations/mercadolivre/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsMercadolivreCallbackRoute =
  ApiPublicIntegrationsMercadolivreCallbackRouteImport.update({
    id: '/api/public/integrations/mercadolivre/callback',
    path: '/api/public/integrations/mercadolivre/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/integrador': typeof AuthenticatedIntegradorRoute
  '/feed/estoque.json': typeof FeedEstoqueDotjsonRoute
  '/integracoes/mercado-livre': typeof AuthenticatedIntegracoesMercadoLivreRoute
  '/api/public/vehicle-image': typeof ApiPublicVehicleImageRoute
  '/api/public/integrations/mercadolivre/callback': typeof ApiPublicIntegrationsMercadolivreCallbackRoute
  '/api/public/integrations/mercadolivre/notifications': typeof ApiPublicIntegrationsMercadolivreNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/integrador': typeof AuthenticatedIntegradorRoute
  '/feed/estoque.json': typeof FeedEstoqueDotjsonRoute
  '/integracoes/mercado-livre': typeof AuthenticatedIntegracoesMercadoLivreRoute
  '/api/public/vehicle-image': typeof ApiPublicVehicleImageRoute
  '/api/public/integrations/mercadolivre/callback': typeof ApiPublicIntegrationsMercadolivreCallbackRoute
  '/api/public/integrations/mercadolivre/notifications': typeof ApiPublicIntegrationsMercadolivreNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acesso': typeof AcessoRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/integrador': typeof AuthenticatedIntegradorRoute
  '/feed/estoque.json': typeof FeedEstoqueDotjsonRoute
  '/_authenticated/integracoes/mercado-livre': typeof AuthenticatedIntegracoesMercadoLivreRoute
  '/api/public/vehicle-image': typeof ApiPublicVehicleImageRoute
  '/api/public/integrations/mercadolivre/callback': typeof ApiPublicIntegrationsMercadolivreCallbackRoute
  '/api/public/integrations/mercadolivre/notifications': typeof ApiPublicIntegrationsMercadolivreNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso'
    | '/admin'
    | '/sitemap.xml'
    | '/integrador'
    | '/feed/estoque.json'
    | '/integracoes/mercado-livre'
    | '/api/public/vehicle-image'
    | '/api/public/integrations/mercadolivre/callback'
    | '/api/public/integrations/mercadolivre/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso'
    | '/admin'
    | '/sitemap.xml'
    | '/integrador'
    | '/feed/estoque.json'
    | '/integracoes/mercado-livre'
    | '/api/public/vehicle-image'
    | '/api/public/integrations/mercadolivre/callback'
    | '/api/public/integrations/mercadolivre/notifications'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acesso'
    | '/admin'
    | '/sitemap.xml'
    | '/_authenticated/integrador'
    | '/feed/estoque.json'
    | '/_authenticated/integracoes/mercado-livre'
    | '/api/public/vehicle-image'
    | '/api/public/integrations/mercadolivre/callback'
    | '/api/public/integrations/mercadolivre/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcessoRoute: typeof AcessoRoute
  AdminRoute: typeof AdminRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FeedEstoqueDotjsonRoute: typeof FeedEstoqueDotjsonRoute
  ApiPublicVehicleImageRoute: typeof ApiPublicVehicleImageRoute
  ApiPublicIntegrationsMercadolivreCallbackRoute: typeof ApiPublicIntegrationsMercadolivreCallbackRoute
  ApiPublicIntegrationsMercadolivreNotificationsRoute: typeof ApiPublicIntegrationsMercadolivreNotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/estoque.json': {
      id: '/feed/estoque.json'
      path: '/feed/estoque.json'
      fullPath: '/feed/estoque.json'
      preLoaderRoute: typeof FeedEstoqueDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/integrador': {
      id: '/_authenticated/integrador'
      path: '/integrador'
      fullPath: '/integrador'
      preLoaderRoute: typeof AuthenticatedIntegradorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/vehicle-image': {
      id: '/api/public/vehicle-image'
      path: '/api/public/vehicle-image'
      fullPath: '/api/public/vehicle-image'
      preLoaderRoute: typeof ApiPublicVehicleImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/integracoes/mercado-livre': {
      id: '/_authenticated/integracoes/mercado-livre'
      path: '/integracoes/mercado-livre'
      fullPath: '/integracoes/mercado-livre'
      preLoaderRoute: typeof AuthenticatedIntegracoesMercadoLivreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/integrations/mercadolivre/notifications': {
      id: '/api/public/integrations/mercadolivre/notifications'
      path: '/api/public/integrations/mercadolivre/notifications'
      fullPath: '/api/public/integrations/mercadolivre/notifications'
      preLoaderRoute: typeof ApiPublicIntegrationsMercadolivreNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/mercadolivre/callback': {
      id: '/api/public/integrations/mercadolivre/callback'
      path: '/api/public/integrations/mercadolivre/callback'
      fullPath: '/api/public/integrations/mercadolivre/callback'
      preLoaderRoute: typeof ApiPublicIntegrationsMercadolivreCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIntegradorRoute: typeof AuthenticatedIntegradorRoute
  AuthenticatedIntegracoesMercadoLivreRoute: typeof AuthenticatedIntegracoesMercadoLivreRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIntegradorRoute: AuthenticatedIntegradorRoute,
  AuthenticatedIntegracoesMercadoLivreRoute:
    AuthenticatedIntegracoesMercadoLivreRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcessoRoute: AcessoRoute,
  AdminRoute: AdminRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FeedEstoqueDotjsonRoute: FeedEstoqueDotjsonRoute,
  ApiPublicVehicleImageRoute: ApiPublicVehicleImageRoute,
  ApiPublicIntegrationsMercadolivreCallbackRoute:
    ApiPublicIntegrationsMercadolivreCallbackRoute,
  ApiPublicIntegrationsMercadolivreNotificationsRoute:
    ApiPublicIntegrationsMercadolivreNotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
